<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta equiv="X-UA-Compatible" content="IE=EDGE">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{% block title %}todo list{% endblock %}</title>
  {% block styles %}
    <link rel="stylesheet" href="">
  {% endblock %}
</head>
<body>
  {% block main %}{% endblock %}
  {% block scripts %}
  {% endblock %}
</body>
</html>
